Models/Distribuidor.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Contracts;
namespace T2_QUIROZ_MIGUEL.Models
{
    public class Distribuidor
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El nombre del Distribuidor es obligatorio")]
        public string NombreDistribuidor { get; set; }
        [Required(ErrorMessage = "La razon social es obligatorio")]
        public string RazonSocial { get; set; }
        [Required(ErrorMessage = "El numero de Telefono es obligatorio")]
        public int Telefono { get; set; }
        //AnioInicioOperacion debe tener un rango de 1900 a 3000
        [Required(ErrorMessage = "El Año de Inicio de Operacion es Obligatorio es obligatorio")]
        [Range(1900, 3000, ErrorMessage = "El Año de Inicio debe ser entre 1900 y 3000")]
        public int AnioInicioOperacion { get; set; }
        [Required(ErrorMessage = "El contacto es obligatorio")]
        public string Contacto { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace T2_QUIROZ_MIGUEL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DistribuidorController.cs
using Microsoft.AspNetCore.Mvc;
using T2_QUIROZ_MIGUEL.Datos;
using T2_QUIROZ_MIGUEL.Models;

namespace T2_QUIROZ_MIGUEL.Controllers
{
    public class DistribuidorController : Controller
    {
        private readonly ApplicationDbContext _db;
        public DistribuidorController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Distribuidor> lista = _db.Distribuidor;
            return View(lista);
        }
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Add(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);

        }

        //Get Editar
        public IActionResult Editar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //Post Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Update(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);

        }

        //Get Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //Post Eliminar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Distribuidor distribuidor)
        {
            if (distribuidor == null)
            {
                return NotFound();
            }
            _db.Distribuidor.Remove(distribuidor);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));


        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using T2_QUIROZ_MIGUEL.Models;

namespace T2_QUIROZ_MIGUEL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Distribuidor/Crear.cshtml
@model T2_QUIROZ_MIGUEL.Models.Distribuidor;
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<form method="post" asp-action="Crear">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-intro pl-3">Nuevo Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre del Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control" />
                    <span asp-validation-for="NombreDistribuidor" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">Razon Social</label>
                    <input asp-for="RazonSocial" class="form-control" />
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año de Inicio de Operacion</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                    <span asp-validation-for="AnioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grid gap-2 d-md-block">

                <button type="submit" class="btn btn-primary">Crear Nueva</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>

            </div>

        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}                    

Views/Distribuidor/Editar.cshtml
@model T2_QUIROZ_MIGUEL.Models.Distribuidor;
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<form method="post" asp-action="Editar">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-intro pl-3">Editar Categoria</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control" />
                    <span asp-validation-for="NombreDistribuidor" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">RazonSocial</label>
                    <input asp-for="RazonSocial" class="form-control" />
                    <span asp-validation-for="RazonSocial" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año de Inicio de Operacion</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                    <span asp-validation-for="AnioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                    <span asp-validation-for="Contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grid gap-2 d-md-block">

                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>

            </div>

        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}                 

Views/Distribuidor/Eliminar.cshtml
@model T2_QUIROZ_MIGUEL.Models.Distribuidor;
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>


<form method="post" asp-action="Eliminar">
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-intro pl-3">¿Está seguro de Eliminar a este Distribuidor?</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreDistribuidor" class="form-label">Nombre Distribuidor</label>
                    <input asp-for="NombreDistribuidor" class="form-control" />
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="RazonSocial" class="form-label">RazonSocial</label>
                    <input asp-for="RazonSocial" class="form-control" />
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="AnioInicioOperacion" class="form-label">Año de Inicio de Operacion</label>
                    <input asp-for="AnioInicioOperacion" class="form-control" />
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Contacto" class="form-label">Contacto</label>
                    <input asp-for="Contacto" class="form-control" />
                </div>
            </div>

            <div class="d-grid gap-2 d-md-block">

                <button type="submit" class="btn btn-primary">Eliminar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>

            </div>

        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}                 

Views/Distribuidor/Index.cshtml
@model IEnumerable<T2_QUIROZ_MIGUEL.Models.Distribuidor>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div class="container pt-3">

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Lista de Distribuidores</h2>

        </div>
        <div class="col-6">
            <a asp-controller="Distribuidor" asp-action="Crear" class="btn btn-primary">Nuevo Distribuidor</a>
        </div>

    </div>

    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> Nombre Distribuidor </th>
                    <th> Razon Social </th>
                    <th> Telefono </th>
                    <th> Año de Inicio de Operacion </th>
                    <th> Contacto </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="40%">@item.NombreDistribuidor</th>
                        <th width="30%">@item.RazonSocial</th>
                        <th width="20%">@item.Telefono</th>
                        <th width="20%">@item.AnioInicioOperacion</th>
                        <th width="30%">@item.Contacto</th>
                        <th>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Distribuidor" asp-action="Editar" asp-route-Id="@item.Id" class="btn btn-primary mx-2">Editar</a>
                                <a asp-controller="Distribuidor" asp-action="Eliminar" asp-route-Id="@item.Id" class="btn btn-danger mx-2">Eliminar</a>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {

        <p>No hay registros en la categoria</p>
    }

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Esta es mi T2</h1>
    <h1 class="display-4"> Miguel Quiroz N00316173</h1>
    <img src="https://media.tenor.com/8UMci6fGKosAAAAM/swag-club-penguin.gif" alt="GIF DE PINGUINO LINUX BAILANDO CON FLOW" width="300" height="200">
    <p>Github Username: migderMM</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T2_QUIROZ_MIGUEL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T2_QUIROZ_MIGUEL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T2_QUIROZ_MIGUEL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Index">Distribuidor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - T2_QUIROZ_MIGUEL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>